plugins {
    id "com.android.library"
}

group 'com.baidu.flutter_baidu_mapapi_map'
version '1.0'

//buildscript {
//    repositories {
//        google()
//        mavenCentral()
//        maven { url 'https://maven.aliyun.com/repository/google' }
//        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
//        maven { url 'https://maven.aliyun.com/repository/jcenter'}
//        maven { url 'https://maven.aliyun.com/repository/content/groups/public' }
//
////        maven { url "https://storage.googleapis.com/download.flutter.io" }
////        maven { url 'http://download.flutter.io' }
////        google()
////        jcenter()
//    }
//
//    dependencies {
//        classpath 'com.android.tools.build:gradle:7.3.0'
//    }
//}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/public' }
//        google()
//        jcenter()
    }
}

//apply plugin: 'com.android.library'

android {
    compileSdkVersion 35

    namespace 'com.baidu.bmfmap'

    defaultConfig {
        minSdkVersion 22
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    sourceSets {
        main {
            jniLibs.srcDir 'libs'
        }
    }

}

repositories {
    flatDir {
        dirs 'libs'
    }
}

repositories {
    mavenLocal()
}


dependencies {
    // implementation fileTree(includes: ['*.jar'], dir: 'libs')
    implementation 'com.baidu.lbsyun:BaiduMapSDK_Map:7.6.6'
    implementation 'com.baidu.lbsyun:BaiduMapSDK_Search:7.6.6'
    implementation 'com.baidu.lbsyun:BaiduMapSDK_Util:7.6.6'
    implementation 'android.arch.lifecycle:extensions:1.1.1'
//    implementation rootProject.findProject(":flutter_baidu_mapapi_base")
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
}
